### PR TITLE
Add rendering support for recurring events

### PR DESCRIPTION
**Pull request by marcauberer**
Add rendering support for recurring events

### CODE REVIEW

**Comment by aldabil21** [comment]
@marcauberer appreciate it
This will bring a lot of other related work, such as: start, end, daysOfWeek etc... or rrule.
I'm not sure if we can go this simple? what do you think

**Comment by marcauberer** [comment]
@aldabil21 Didn't knew rrule, but it looks promising. Yes, maybe this is worth trying. I will prepare an updated pr ...

**Comment by marcauberer** [comment]
@aldabil21 sorry it took so long. I was on vacation. The pr is now updated with rrule support. What do you think?

**Comment by marcauberer** [comment]
@aldabil21 any feedback on this?

**Comment by marcauberer** [comment]
@aldabil21 ping

**Comment by majilan37** [comment]
This is really cool, i am waiting for this feature

**Comment by aldabil21** [comment]
Thank you @marcauberer 
Currenct caveat is, `onDrop` must be override by the user to re-create a rrule.

we can go with this for now

**Comment by marcauberer** [comment]
@aldabil21 thanks for merging. Will take a look at onDrop soon.

**Pull request merged**
