### PR TITLE
Adding new prop (showAddEvent) to the schedular component

### PR DESCRIPTION
**Pull request by NiharR27**
It gives ability to the user to allow user to click the cell to add an event or not.

### CODE REVIEW

**Comment by aldabil21** [comment]
Hi @NiharR27 

Thank you for the PR

I'm not sure exactly why I totally forgot about it and didn't mention it in the README as well, but you can actually controll the cell click _cell-wise_ insted of _table-wise_ matter as this PR proppose.

By using `cellRenderer` function in `week` & `day` props you can controll each cell condition given the helper `props` here
https://github.com/aldabil21/react-scheduler/blob/cd196878c64abf21e693b7303d566dc87e720edb/src/lib/views/Week.tsx#L46

Example would be like:

```
<Scheduler
// ... options
week={{
    startHour: 9,
    endHour: 14,
    step: 60,
    weekDays: [0, 1, 2, 3, 4],
    weekStartOn: 1,
    cellRenderer: ({ height, start, onClick }) => {
      // Fake some condition up
      const hour = start.getHours();
      const disabled = hour === 11;
      if(disabled){
        return <div style={{
          cursor: "not-allowed",
          height,
          display:"flex",
          alignItems:"center",
          justifyContent:"center",
          color:"#ccc"
        }}>
          X
        </div>
      }
      return (
        <button
          style={{
            width: "100%",
            height,
            margin: 0,
            border: 0,
            cursor: "pointer",
            background: "transparent"
          }}
          onClick={onClick}
        ></button>
      );
    }
}}
/>
```
Try it out and let me know how it goes.
I'm about to finish a new upgrade soon, which will fix the styles -_which is a total mess_-, and will mention and fix this part.

**Comment by aldabil21** [comment]
A better solution for #5

**Comment by NiharR27** [comment]
Thanks @aldabil21 legend.

**Comment by aldabil21** [comment]
@NiharR27 
Check this out: https://codesandbox.io/s/custom-cell-action-n02dv

**Pull request closed without merging**
