### PR TITLE
Upgrade to @mui/x-date-pickers v6

### PR DESCRIPTION
**Pull request by jackstenglein**
https://mui.com/x/migration/migration-pickers-v5/

- Uses the new `slots` or `slotProps` props on the DatePicker/DateTimePicker where appropriate
- Uses `DateCalendarProps` renamed from `CalendarPickerProps`

### CODE REVIEW

**Review by aldabil21 — CHANGES_REQUESTED** [review]
Awesome, appreciate the efforts buddy.

This looks nice, but currently has 2 issues:
1. The `params.inputRef` should be in an input element not button, so the popper will be off, there is an error message about it in the conosle. you could change it to `params.InputProps?.ref as RefObject<HTMLButtonElement>`, this will fix it, but when you close the popper it flickers. I could not find a solution for that, if you can, please push it :+1: 
Screenshot from 2023-03-17 15-54-55

2. Update `peerDependencies` for `@mui/x-date-pickers`

**Comment by jackstenglein** [comment]
@aldabil21 I improved the MonthDateBtn slightly. Now if you close the dialog by clicking outside of it, it closes without flickering. However, if you choose a new month, it flickers. It seems to flicker when the DatePicker is rerendered. I'm not sure how to fix it but maybe my findings here will give you some inspiration?

**Comment by jackstenglein** [comment]
I think I may have found a solution actually. I will have an updated version ready soon.

**Comment by jackstenglein** [comment]
@aldabil21 I think this version should be ready now. Let me know if anything else needs to be updated.

**Comment by aldabil21** [comment]
well done Jack :rocket:

**Pull request merged**
